import sqlite3
from sqlite3 import Error

def create_connection():
    conn = None;
    try:
        conn = sqlite3.connect('lean_management_quiz.db')  # create a database connection to a SQLite database 
        print(sqlite3.version)
    except Error as e:
        print(e)
    return conn

def insert_question(conn, question_text, correct_answer, option_1, option_2, option_3, option_4, category_id):
    cur = conn.cursor()
    cur.execute("INSERT INTO questions(question_text, correct_answer, option_1, option_2, option_3, option_4, category_id) VALUES(?, ?, ?, ?, ?, ?, ?)", 
    (question_text, correct_answer, option_1, option_2, option_3, option_4, category_id))
    conn.commit()

def main():
    database = r"lean_management_quiz.db"
    conn = create_connection()
    questions = [
    {
        'question_text': 'What is the value stream and how is it identified in lean management?',
        'correct_answer': 'a) The value stream is the sequence of activities that create value for the customer. It is identified through value stream mapping.',
        'options': [
            'a) The value stream is the sequence of activities that create value for the customer. It is identified through value stream mapping.',
            'b) The value stream is the flow of resources within an organization. It is identified through process analysis.',
            'c) The value stream is the financial value generated by a process. It is identified through cost analysis.',
            'd) The value stream is the customer\'s perception of value. It is identified through customer feedback.'
        ]
    },
    {
        'question_text': 'How does inventory in software development compare to inventory in manufacturing?',
        'correct_answer': 'b) Inventory in software development refers to the codebase and software components, while inventory in manufacturing refers to raw materials and finished goods.',
        'options': [
            'a) Inventory in software development refers to physical goods, while inventory in manufacturing refers to digital assets.',
            'b) Inventory in software development refers to the codebase and software components, while inventory in manufacturing refers to raw materials and finished goods.',
            'c) Inventory in software development refers to customer orders, while inventory in manufacturing refers to work-in-progress items.',
            'd) Inventory is not applicable in software development, as it is a non-physical industry.'
        ]
    }
]

    for question in questions:
            insert_question(conn, question['question_text'], question['correct_answer'], *question['options'], 2)

if __name__ == "__main__":
    main()
